import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Importing Inter from Google Fonts
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";

// Importing Inter font from Google Fonts
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Define a variable for the Inter font
});

// Importing local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

// Metadata for the document
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistSans.variable} ${geistMono.variable}`} // Apply all font variables
    >
      <Providers>
        <body className={inter.className}>{children}</body> {/* Use Inter font by default */}
      </Providers>
    </html>
  );
}
